name: DevSecOps Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  sast:
    name: SAST - Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install bandit
      - run: bandit -r part1/app_secure.py --severity-level high

  sca:
    name: SCA - pip-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pip-audit
      - run: pip-audit -r requirements.txt || true

  security-tests:
    name: Security Tests - pytest
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: cp part2/test_security.py part1/
      - run: cd part1 && pytest test_security.py -v
